network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 192.168.200.130/24
      routes:
        - to: default
          via: 192.168.200.2
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
